{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[{"file_id":"1VpjNj32Gy9OXbXyW8vqs6JL3XRVLXViR","timestamp":1740088901174},{"file_id":"1pE-UHn_CJaK0f9U512Zi3-Wh4ExbLbhX","timestamp":1673235589514},{"file_id":"15sbGtGNYqiA2RFUHNJEWNYVck3djlH3h","timestamp":1673032067739},{"file_id":"13AYIRXtA4NaoB-xZET7nkPmcrU82Z2Ly","timestamp":1672006887600},{"file_id":"1B1OgfeYODfag9g4JltvYlVZSYGtRm5ky","timestamp":1655836534802}],"collapsed_sections":["EGuQvJg0gCMX","I47v1KCJfHv7","ALu5wndVEfp9","7ANtghTjk7po","krF8uDUJEo9e","pLraTLRw8Bci","uMV5WkhADib1","iCQeNDvh81TV","9_OE9xI9EsR0","CzVMF_ED-U0W","H1y_YHlkBe6L","u0w3xvDrBfHx","jRURX77UEv1c"]},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"markdown","source":["![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)\n","\n","# **$$ðŸ”¶ \\textbf{   The Most Common Errors in Python and How to Fix them  }ðŸ”¶$$**"],"metadata":{"id":"i-6TEOkxg6W2"}},{"cell_type":"markdown","source":["Objective:\n","* Learn the most common error types in Python.\n","* Read the error message to identify the type and lines of code where the errors occur."],"metadata":{"id":"2b96P7LOecaV"}},{"cell_type":"markdown","source":["![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)\n","# **Introduction**\n"],"metadata":{"id":"EGuQvJg0gCMX"}},{"cell_type":"markdown","source":["---\n","## **The traceback** message has multiple carets (**<font color= \"red\"><strong>^</strong></font>**) showing where the invalid syntax was encountered. While it sometimes might not pinpoint the exact location, it will usually hint at the issue's probable location"],"metadata":{"id":"4-jEbJpJljFZ"}},{"cell_type":"markdown","source":["|Error Type| Trace Back Identifier|Explaination|\n","|--|--|--|\n","|Syntaxes|`SyntaxError`|Typo or other mistake in your code|\n","|Indentation|`IndentationError`|Python uses whitespace to indicate blocks of code, so proper indentation is critical|\n","|Names|`NameError`| Occurs when you try to use a variable or function that hasn't been defined or might be out of scope. <br> It occurs when referencing a variable before its assignment or misspelling an identifier: |\n","|Types|`TypeError`| Occurs when you try to operate on data type, not supported or appropriate for the object data type |\n","|Indices| `IndexError`|Occur when you try to access an item in a list or other sequence using an index that is out of range|\n","|Values| `ValueError`|A function received an argument of the correct data type; however, the value itself is invalid.|\n","|Keys| `KeyError`|Occur when you try to access a dictionary using a key that doesn't exist|\n"],"metadata":{"id":"lbywOxf_gw0U"}},{"cell_type":"markdown","source":["![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)\n","# $$ ðŸ”– \\,\\mathbf{ \\,\\,1. \\,\\,} \\color{blue}{\\textbf{Practice:}}\\color{red}{\\textbf{ Syntax}} \\textbf{ Errors Samples} $$\n"],"metadata":{"id":"I47v1KCJfHv7"}},{"cell_type":"markdown","source":["Some common causes of SyntaxError include:\n","\n","* Unclosed strings\n","* Indentation issues\n","* Misusing the assignment operator (=)\n","* Misspelling Python keywords\n","* Missing brackets, parentheses, or braces\n","* Using newer Python syntax on an old version of Python.\n","\n","When this error occurs, a traceback is produced to help you determine where the problem is. Take the following example:"],"metadata":{"id":"GrUfYwQrkOw6"}},{"cell_type":"markdown","source":["In this example, we are trying to assign the value 10 to the variable x using the assignment operator (`=`) inside an if statement.\n","\n","But the correct syntax for comparing values in an if statement is to use the comparison operator (`==`).\n","\n","So here's how you fix this one:"],"metadata":{"id":"kHUGg8PWkk5d"}},{"cell_type":"markdown","source":["##$ðŸ”– \\, \\color{green}{\\textbf{TODO 1:}}$\n","\n","**1. Run the following code cell.**\\\n","**2. Identify the type of errors and write the corrected code below:**"],"metadata":{"id":"ALu5wndVEfp9"}},{"cell_type":"code","source":["# The error that is generated is a SyntaxError because the types of quotation marks do not match\n","print(\"This is a string.')"],"metadata":{"id":"yxbo5TKRc7DT","colab":{"base_uri":"https://localhost:8080/","height":106},"executionInfo":{"status":"error","timestamp":1740094027087,"user_tz":480,"elapsed":9,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"8f15b444-2570-44b1-e2d1-d6a756f0dd28"},"execution_count":null,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"unterminated string literal (detected at line 1) (<ipython-input-1-a72406ded630>, line 1)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-a72406ded630>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    print(\"This is a string.')\u001b[0m\n\u001b[0m          ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m unterminated string literal (detected at line 1)\n"]}]},{"cell_type":"code","source":["# The corrected code has matching quotation marks\n","print(\"This is a string.\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"plC2EZOCr8Om","executionInfo":{"status":"ok","timestamp":1740267537888,"user_tz":480,"elapsed":12,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"62284e6b-0da6-4ba6-ab35-1ee02f231859"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["This is a string.\n"]}]},{"cell_type":"markdown","source":["![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)\n","# $$ ðŸ”– \\,\\mathbf{ \\,\\,2. \\,\\,} \\color{blue}{\\textbf{Practice:}} \\color{red}{\\textbf{ Indentation}} \\textbf{ Errors Samples} $$"],"metadata":{"id":"7ANtghTjk7po"}},{"cell_type":"markdown","source":["Here are a few rules to keep in mind when it comes to indentation in Python:\n","\n","* Use four spaces for each level of indentation.\n","* Don't mix tabs and spaces for indentation.\n","* Make sure your indentation is consistent throughout your code."],"metadata":{"id":"z9BSmSrk67Cd"}},{"cell_type":"markdown","source":["Here are a few rules to keep in mind when it comes to indentation in Python:\n","\n","* Use four spaces for each level of indentation.\n","* Don't mix tabs and spaces for indentation.\n","* Make sure your indentation is consistent throughout your code.\n","\n","The above code could be corrected with correct level of indentations"],"metadata":{"id":"hChBSjm47qjc"}},{"cell_type":"markdown","source":["##$ðŸ”– \\, \\color{green}{\\textbf{TODO 2:}}$\n","**1. Run the following code cell.**\\\n","**2. Identify the type of errors and write the corrected code below:**"],"metadata":{"id":"krF8uDUJEo9e"}},{"cell_type":"code","source":["# The print() statement produces an error because it is not indented correctly with 8 spaces\n","for i in range(5):\n","    if i // 2 == 0:\n","    print(f\" {i} is an even number\")"],"metadata":{"id":"goDnsr3VXy7K","colab":{"base_uri":"https://localhost:8080/","height":110},"executionInfo":{"status":"error","timestamp":1740267565802,"user_tz":480,"elapsed":2,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"d6681c8e-0d52-42f7-fe2b-758c65d94197"},"execution_count":2,"outputs":[{"output_type":"error","ename":"IndentationError","evalue":"expected an indented block after 'if' statement on line 2 (<ipython-input-2-bf1a3ee32a9e>, line 3)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-2-bf1a3ee32a9e>\"\u001b[0;36m, line \u001b[0;32m3\u001b[0m\n\u001b[0;31m    print(f\" {i} is an even number\")\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m expected an indented block after 'if' statement on line 2\n"]}]},{"cell_type":"code","source":["# The code is now indented correctly\n","for i in range(5):\n","    if i // 2 == 0:\n","        print(f\" {i} is an even number\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"dlugF_PvswJH","executionInfo":{"status":"ok","timestamp":1740267602189,"user_tz":480,"elapsed":3,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"3886a613-2c11-4048-c6dc-4787e7cf2072"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":[" 0 is an even number\n"," 1 is an even number\n"]}]},{"cell_type":"code","source":["# This produces an indentation error (from the second print() statment) because it is not indented at the\n","# same level as the previous print statement\n","if 5 > 2:\n"," print(\"Five is greater than two!\")\n","        print(\"Five is greater than two!\")"],"metadata":{"id":"NDKKHtJJYH_m","colab":{"base_uri":"https://localhost:8080/","height":110},"executionInfo":{"status":"error","timestamp":1740267621256,"user_tz":480,"elapsed":7,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"b1c707bb-ec65-4cd1-d5b9-9a09031507fc"},"execution_count":4,"outputs":[{"output_type":"error","ename":"IndentationError","evalue":"unexpected indent (<ipython-input-4-75258082a17d>, line 5)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-4-75258082a17d>\"\u001b[0;36m, line \u001b[0;32m5\u001b[0m\n\u001b[0;31m    print(\"Five is greater than two!\")\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m unexpected indent\n"]}]},{"cell_type":"code","source":["if 5 > 2:\n","    print(\"Five is greater than two!\")\n","    print(\"Five is greater than two!\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"S3NMxu_8s08u","executionInfo":{"status":"ok","timestamp":1740267623781,"user_tz":480,"elapsed":5,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"d2c0bfca-1762-4c5b-a4af-c7bf2c1fe8e4"},"execution_count":5,"outputs":[{"output_type":"stream","name":"stdout","text":["Five is greater than two!\n","Five is greater than two!\n"]}]},{"cell_type":"markdown","source":["![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)\n","# $$ ðŸ”– \\,\\mathbf{ \\,\\,3. \\,\\,} \\color{blue}{\\textbf{Practice:}} \\color{red}{\\textbf{ Name}} \\textbf{ Errors Samples} $$"],"metadata":{"id":"pLraTLRw8Bci"}},{"cell_type":"markdown","source":["Python raises a NameError if you attempt to use an identifier that hasn't been defined or might be out of scope. Other potential causes of a NameError include referencing a variable before its assignment or misspelling an identifier:"],"metadata":{"id":"YMt85_iD8Bcq"}},{"cell_type":"markdown","source":["In this example, the name variable is not defined but is being accessed. As a result, Python throws an exception:\n","\n","To fix this problem, ensure that the variable or function name you want to use has been defined. Check for spelling errors and ensure that the variable you want to use is within the scope where it is being accessed."],"metadata":{"id":"3Bd1bGwG8Zb3"}},{"cell_type":"markdown","source":["Here are some tips for avoiding name errors:\n","\n","* Make sure you've defined all variables and functions before using them.\n","* Double-check the spelling and capitalization of your variable and function names.\n","* Use Python's built-in debugging tools, such as print statements, to help you track down name errors."],"metadata":{"id":"2QFG4qJ98jcF"}},{"cell_type":"markdown","source":["##$ðŸ”– \\, \\color{green}{\\textbf{TODO 3:}}$\n","**1. Run the following code cell.**\\\n","**2. Identify the type of errors and write the corrected code below:**"],"metadata":{"id":"uMV5WkhADib1"}},{"cell_type":"code","source":["# the variable `sum_of_2_plus_2` has not been defined, so a NameError is raised\n","print(f\" the sum of 2 plus 2 is {sum_of_2_plus_2}\")"],"metadata":{"id":"67QmpvGsDbJD","colab":{"base_uri":"https://localhost:8080/","height":147},"executionInfo":{"status":"error","timestamp":1740267645101,"user_tz":480,"elapsed":54,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"ff13b5e5-bda8-4439-9025-3434351b20eb"},"execution_count":6,"outputs":[{"output_type":"error","ename":"NameError","evalue":"name 'sum_of_2_plus_2' is not defined","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-6-7ef6c1806875>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\" the sum of 2 plus 2 is {sum_of_2_plus_2}\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mNameError\u001b[0m: name 'sum_of_2_plus_2' is not defined"]}]},{"cell_type":"code","source":["# We define `sum_of_2_plus_2` so that the code runs correctly\n","sum_of_2_plus_2 = 4\n","print(f\" the sum of 2 plus 2 is {sum_of_2_plus_2}\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"eAXyb8oHCUkM","executionInfo":{"status":"ok","timestamp":1740267697122,"user_tz":480,"elapsed":3,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"305437b5-87f9-4164-d67d-07f90b456693"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":[" the sum of 2 plus 2 is 4\n"]}]},{"cell_type":"markdown","source":["![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)\n","# $$ ðŸ”– \\,\\mathbf{ \\,\\,4. \\,\\,} \\color{blue}{\\textbf{Practice:}} \\color{red}{\\textbf{ Type}} \\textbf{ Errors Samples} $$"],"metadata":{"id":"iCQeNDvh81TV"}},{"cell_type":"markdown","source":["Another common error in Python is type errors. Type errors occur when you try to perform an operation on data of the wrong type. For example, you might try to add a string and a number, or you might try to access an attribute of an object that doesn't exist.\n","\n","Here are some tips for avoiding type errors:\n","\n","* Use type annotations in your code to make it clear what types of data you expect.\n","* Use Python `type()` to check types and `str`, `int` or `float` to convert from one type to another."],"metadata":{"id":"360FMEIE81Te"}},{"cell_type":"markdown","source":["##$ðŸ”– \\, \\color{green}{\\textbf{TODO 4:}}$\n","**1. Run the following code cell.**\\\n","**2. Identify the type of errors and write the corrected code below:**"],"metadata":{"id":"9_OE9xI9EsR0"}},{"cell_type":"code","source":["# A TypeError is raised because we are trying to add a string with an integer\n","x = \"twenty\"\n","y = 20\n","print(f\"Twenty plus 20 = {x + y}  = 40\")"],"metadata":{"id":"CcbQ07GLNvHj","colab":{"base_uri":"https://localhost:8080/","height":184},"executionInfo":{"status":"error","timestamp":1740267719105,"user_tz":480,"elapsed":50,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"c2a56447-9e2c-4fb1-9851-b6ea662746fa"},"execution_count":8,"outputs":[{"output_type":"error","ename":"TypeError","evalue":"can only concatenate str (not \"int\") to str","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-8-ac851112720d>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"twenty\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m20\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"Twenty plus 20 = {x + y}  = 40\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mTypeError\u001b[0m: can only concatenate str (not \"int\") to str"]}]},{"cell_type":"code","source":["# Switching `\"twenty\"` to `20` makes our code run correctly\n","x = 20\n","y = 24\n","print(f\"Twenty plus 20 = {x + y}  = 40\")"],"metadata":{"id":"PawuwRfOR5Kh","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1740267767805,"user_tz":480,"elapsed":4,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"bcd6bc9f-f5c2-4929-baf7-fedbb3df22bb"},"execution_count":10,"outputs":[{"output_type":"stream","name":"stdout","text":["Twenty plus 20 = 44  = 40\n"]}]},{"cell_type":"markdown","source":["![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)\n","# $$ ðŸ”– \\,\\mathbf{ \\,\\,5. \\,\\,} \\color{blue}{\\textbf{Practice:}} \\color{red}{\\textbf{ Index}} \\textbf{ Errors Samples} $$"],"metadata":{"id":"CzVMF_ED-U0W"}},{"cell_type":"markdown","source":["Index errors occur when you try to access an item in a list or other sequence using an index that is out of range. For example, if you try to access the fifth item in a list that only has four items, you'll get an index error.\n"],"metadata":{"id":"O5lExvbhAVHM"}},{"cell_type":"markdown","source":["Recall that in computer science, the index of a data structure starts at 0.  In this example, we are trying to access an item at index 5, which is outside the range of the list with indices from 0 to 3.\n"],"metadata":{"id":"yolo1PMlAduW"}},{"cell_type":"markdown","source":["Here are some tips for avoiding index errors:\n","\n","* Make sure you're using the correct index values for your sequence.\n","* Use Python's built-in functions, such as len, to determine the length of your sequence before trying to access items in it.\n","* Use exception handling, such as try and except blocks, to handle index errors gracefully."],"metadata":{"id":"02-jfKeUAYVn"}},{"cell_type":"markdown","source":["##$ðŸ”– \\, \\color{green}{\\textbf{TODO 5:}}$\n","**1. Run the following code cell.**\\\n","**2. Identify the type of errors and write the corrected code below:**"],"metadata":{"id":"H1y_YHlkBe6L"}},{"cell_type":"code","source":["# An IndexError is raised because defined list has no index 5\n","my_courses = [ \"STAT 050\", \"HIST 010\", \"ART 001\", \"ACC 002\" ]\n","print(f\"The Accounting course I am taking is {my_courses[5]}\")"],"metadata":{"id":"XVdytFrAJoaI","colab":{"base_uri":"https://localhost:8080/","height":166},"executionInfo":{"status":"error","timestamp":1740267811974,"user_tz":480,"elapsed":42,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"b598d255-62ca-4608-977e-cbd8a339fa92"},"execution_count":11,"outputs":[{"output_type":"error","ename":"IndexError","evalue":"list index out of range","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-11-7295b7d498d0>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mmy_courses\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m \u001b[0;34m\"STAT 050\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"HIST 010\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"ART 001\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"ACC 002\"\u001b[0m \u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"The Accounting course I am taking is {my_courses[5]}\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mIndexError\u001b[0m: list index out of range"]}]},{"cell_type":"code","source":["my_courses = [ \"STAT 050\", \"HIST 010\", \"ART 001\", \"ACC 002\" ]\n","print(f\"The Accounting course I am taking is {my_courses[3]}\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"5GrprGG9C47F","executionInfo":{"status":"ok","timestamp":1740267830728,"user_tz":480,"elapsed":5,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"a4215c75-9dde-4eae-fe73-46d4d6ef3689"},"execution_count":12,"outputs":[{"output_type":"stream","name":"stdout","text":["The Accounting course I am taking is ACC 002\n"]}]},{"cell_type":"markdown","source":["![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)\n","# $$ ðŸ”– \\,\\mathbf{ \\,\\,6. \\,\\,} \\color{blue}{\\textbf{Practice:}} \\color{red}{\\textbf{ Value}} \\textbf{ Errors Samples} $$"],"metadata":{"id":"u0w3xvDrBfHx"}},{"cell_type":"markdown","source":["The ValueError exception indicates that a function received an argument of the correct data type; however, the value itself is invalid.  For example, the int() method accepts only integer string like \"42\", and passing something like \"forty-two\" will yield a ValueError:\n"],"metadata":{"id":"lA9mFGHOBfHy"}},{"cell_type":"markdown","source":["Another common cause is passing an empty iterable to the max() or min() built-in functions, e.g., max([]).\n","\n","To resolve this issue, provide the correct data type and value as an argument to the built-in functions. Check the documentation for the specific function you're using to ensure compliance with expected input formats."],"metadata":{"id":"b-vW9QjTB6-y"}},{"cell_type":"markdown","source":["##$ðŸ”– \\, \\color{green}{\\textbf{TODO 6:}}$\n","**1. Run the following code cell.**\\\n","**2. Identify the type of errors and write the corrected code below:**"],"metadata":{"id":"jRURX77UEv1c"}},{"cell_type":"code","source":["# The ValueError is raised because although we are using a correct type (int), we cannot take the square root of a negative number\n","import math\n","\n","print(f\"The square root of -1 is {math.sqrt(-1)}\")"],"metadata":{"id":"6WZYQv4KGLhL","colab":{"base_uri":"https://localhost:8080/","height":184},"executionInfo":{"status":"error","timestamp":1740267897057,"user_tz":480,"elapsed":22,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"b9f80071-d722-403a-ef68-6ae6f212f6af"},"execution_count":13,"outputs":[{"output_type":"error","ename":"ValueError","evalue":"math domain error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-13-53dcab5a4076>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmath\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"The square root of -1 is {math.sqrt(-1)}\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mValueError\u001b[0m: math domain error"]}]},{"cell_type":"code","source":["import math\n","\n","print(f\"The square root of 1 is {math.sqrt(1)}\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"BGQ6pyBEDMBX","executionInfo":{"status":"ok","timestamp":1740267951284,"user_tz":480,"elapsed":2,"user":{"displayName":"Timothy Sanders","userId":"01760625927312570070"}},"outputId":"c2ee5490-4c8a-4d9d-d8d8-a7aaf36f4110"},"execution_count":15,"outputs":[{"output_type":"stream","name":"stdout","text":["The square root of 1 is 1.0\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"STkadtiTDXo5"},"execution_count":null,"outputs":[]}]}